# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Suga < Formula
  desc "Suga CLI"
  homepage "https://app.addsuga.com/"
  version "0.0.10"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nitrictech/suga/releases/download/v0.0.10/suga_0.0.10_darwin_amd64.tar.gz"
      sha256 "344fd176accd837416f923cc094cd522b9b9f8c929bdf156e39d86db6f3a6d53"

      def install
        bin.install "suga"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nitrictech/suga/releases/download/v0.0.10/suga_0.0.10_darwin_arm64.tar.gz"
      sha256 "b18b3cf873a58ff7d4e4f8a427704c5b279c283630e2f9c9947ef7efbf22ff6e"

      def install
        bin.install "suga"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nitrictech/suga/releases/download/v0.0.10/suga_0.0.10_linux_amd64.tar.gz"
      sha256 "cf367863e77cb3d1594487cee4e828551cbfa58b8a454e6f30b6aa9d65b0905e"
      def install
        bin.install "suga"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nitrictech/suga/releases/download/v0.0.10/suga_0.0.10_linux_arm64.tar.gz"
      sha256 "700a7c36bf9c7df5ac4d94a180cfaa3392bd51b6b7d0f83889f2ec1a1a4d1f96"
      def install
        bin.install "suga"
      end
    end
  end
end
