# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Suga < Formula
  desc "Suga CLI"
  homepage "https://app.addsuga.com/"
  version "0.0.3"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nitrictech/suga/releases/download/v0.0.3/suga_0.0.3_darwin_amd64.tar.gz"
      sha256 "ce57b3196fcee6f329baf8854f0913ba7d622ac54ee4fad59762a8cfd07d6a4b"

      def install
        bin.install "suga"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nitrictech/suga/releases/download/v0.0.3/suga_0.0.3_darwin_arm64.tar.gz"
      sha256 "0017b44fe90ddfa290a9410f262cc2c7417aad9158b23e4ab3a0b360edd72798"

      def install
        bin.install "suga"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/nitrictech/suga/releases/download/v0.0.3/suga_0.0.3_linux_amd64.tar.gz"
      sha256 "1e7efa29f08dfed2ea1a0ec780261f9421a8ffe8b6fe3961a6cc320e0909255b"
      def install
        bin.install "suga"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/nitrictech/suga/releases/download/v0.0.3/suga_0.0.3_linux_arm64.tar.gz"
      sha256 "991f912504a80d608cc7c1bbbc043c55ab7a2293bbd09774e5daa0205c0daaa0"
      def install
        bin.install "suga"
      end
    end
  end
end
